/*
 * Beispiel-Schlagzeilen für den Bedeutungs-Filter. Selbst formuliert im Stil österreichischer
 * und deutscher Nachrichtenseiten (teils mit Vorspann, weil Teaser oft einen haben). Das
 * Sprachmodell vergleicht jede Meldung mit diesen Beispielen: Liegt sie näher an den
 * belastenden Beispielen der aktivierten Themen als an den harmlosen, wird sie unscharf.
 *
 * Bewusst nicht aus den Testdaten (test/fixtures/real-headlines.json) übernommen, damit die
 * Messung dort ehrlich bleibt.
 */
(function (root) {
  'use strict';

  const BAD = {
    ki: [
      'Neues KI-Modell schreibt Texte und ersetzt Arbeitsplätze',
      'Chatbot erzeugt gefälschte Bilder von Politikern',
      'OpenAI stellt leistungsfähigeres Sprachmodell vor',
      'Künstliche Intelligenz: Experten warnen vor Kontrollverlust',
      'Deepfake-Video eines Ministers sorgt für Verwirrung',
      'Konzern will Hunderte Stellen durch KI-Software ersetzen',
      'KI-Startup sammelt Milliarden bei Investoren ein',
      'Wie ChatGPT den Schulalltag verändert Lehrkräfte berichten von Hausübungen, die vollständig von der KI geschrieben wurden',
      'EU einigt sich auf strengere Regeln für künstliche Intelligenz',
      'Autonome Waffensysteme: Wenn Algorithmen über Leben entscheiden',
      'Google und Microsoft liefern sich Wettrennen um die beste KI',
      'Gesichtserkennung mit KI: Polizei testet neues Überwachungssystem',
    ],
    klima: [
      'Hitzewelle und Dürre: Rekordtemperaturen in Europa',
      'Gletscher schmelzen, Meeresspiegel steigt weiter',
      'Klimakrise: Forscher melden neuen Wärmerekord für die Ozeane',
      'Waldbrände in Südeuropa außer Kontrolle Tausende Menschen mussten ihre Häuser verlassen, Feuerwehren kämpfen gegen die Flammen',
      'CO2-Ausstoß steigt trotz Klimazielen weiter an',
      'Klimawandel bedroht Skigebiete in den Alpen',
      'Wassermangel: Bauern kämpfen mit vertrockneten Feldern',
      'UNO-Bericht: Erderwärmung schreitet schneller voran als erwartet',
      'Extreme Hitze fordert in Indien zahlreiche Todesopfer',
      'Permafrost taut: Bergstürze in den Alpen nehmen zu',
      'Klimaziele verfehlt: Österreich droht Milliardenstrafe',
      'Korallenriffe sterben durch Meereserwärmung',
    ],
    krieg: [
      'Armee startet Offensive, Raketen schlagen in Stadt ein',
      'Kämpfe an der Front: Soldaten getötet, Zivilisten fliehen',
      'Russische Luftangriffe auf ukrainische Energieanlagen',
      'Israelische Armee weitet Bodenoffensive im Gazastreifen aus',
      'Drohnenangriff auf Wohnhaus fordert mehrere Tote',
      'Marine versenkt feindliches Kriegsschiff',
      'Artilleriebeschuss: Dorf an der Grenze schwer zerstört Die Bewohner harren seit Tagen in Kellern aus',
      'Waffenruhe gebrochen: Neue Gefechte im Süden des Landes',
      'Bürgerkrieg im Sudan: Millionen Menschen auf der Flucht',
      'NATO verlegt zusätzliche Truppen an die Ostflanke',
      'Panzer rücken auf die Hauptstadt vor',
      'Kriegsverbrechen: UNO dokumentiert Folter an Gefangenen',
      'Raketenalarm in Tel Aviv, Abfangsysteme im Einsatz',
    ],
    terror: [
      'Anschlag auf Konzert: Attentäter tötet mehrere Menschen',
      'Amoklauf an Schule, Polizei im Großeinsatz',
      'Terrorverdacht: Festnahmen nach geplantem Anschlag auf Bahnhof',
      'Islamistischer Gefährder in Wien festgenommen Der 19-Jährige soll Anschlagspläne im Internet geteilt haben',
      'Explosion vor Botschaft: Ermittler gehen von Terror aus',
      'Geiselnahme in Supermarkt: Spezialeinheit stürmt Gebäude',
      'Schüsse in Einkaufszentrum: Täter auf der Flucht',
      'IS reklamiert Anschlag mit zahlreichen Toten für sich',
      'Messerangriff auf Passanten: Behörden prüfen extremistisches Motiv',
      'Rechtsextreme Terrorzelle plante Anschläge auf Politiker',
      'Bombenalarm am Flughafen: Terminal evakuiert',
    ],
    verbrechen: [
      'Mann nach Messerangriff festgenommen',
      'Überfall auf Pensionistin: Täter flüchtig',
      'Mordprozess: Angeklagter soll Ehefrau erstochen haben',
      'Leiche in Wohnung entdeckt, Polizei ermittelt wegen Mordes',
      'Bewaffneter Raubüberfall auf Juwelier in der Innenstadt',
      'Brutale Schlägerei vor Lokal: Zwei Schwerverletzte',
      'Entführtes Kind nach drei Tagen gefunden',
      'Drogenbande zerschlagen: Waffen und Bargeld sichergestellt',
      'Einbrecherbande festgenommen Die Männer sollen in mehr als 40 Wohnungen eingebrochen sein',
      'Haftstrafe für Betrüger, der Senioren um ihr Erspartes brachte',
      'Schüsse in Wohnsiedlung: Mann lebensgefährlich verletzt',
      'Mordanklage nach tödlichem Streit unter Nachbarn',
    ],
    missbrauch: [
      'Lehrer wegen sexuellen Missbrauchs von Kindern angeklagt',
      'Frau von Ex-Partner geschlagen und vergewaltigt',
      'Femizid in Niederösterreich: Mann tötet seine Partnerin',
      'Missbrauchsskandal in der Kirche: Neue Vorwürfe gegen Priester',
      'Häusliche Gewalt: Zahl der Betretungsverbote steigt deutlich',
      'Opferschutz: Gewalt gegen Frauen bleibt oft unentdeckt',
      'Darstellungen von Kindesmissbrauch auf Computer gefunden',
      'Trainer soll Jugendliche jahrelang sexuell belästigt haben Mehrere ehemalige Spielerinnen haben sich bei der Polizei gemeldet',
      'Frauenhäuser voll: Immer mehr Opfer suchen Schutz',
      'Sexuelle Übergriffe auf Festival: Polizei sucht Zeugen',
    ],
    unglueck: [
      'Gebäude eingestürzt: Bewohner unter Trümmern verschüttet',
      'Schwerer Unfall auf der Autobahn fordert Verletzte',
      'Busunglück: Mehrere Tote und Dutzende Verletzte',
      'Hochwasser: Orte von der Außenwelt abgeschnitten',
      'Erdbeben der Stärke 7 erschüttert die Region',
      'Lawine verschüttet Skitourengeher, Suche läuft',
      'Flugzeugabsturz: Keine Überlebenden gefunden',
      'Großbrand in Lagerhalle, Feuerwehr mit Großaufgebot im Einsatz',
      'Zugunglück: Personenzug entgleist, viele Verletzte',
      'Überschwemmungen nach Unwetter: Keller und Straßen unter Wasser Die Feuerwehren standen die ganze Nacht im Einsatz',
      'Bergsteiger tödlich abgestürzt',
      'Explosion in Chemiefabrik: Anrainer sollen Fenster schließen',
    ],
    tod: [
      'Bekannte Sängerin ist tot',
      'Trauer um verstorbenen Bürgermeister',
      'Schauspieler im Alter von 72 Jahren gestorben',
      'Nachruf: Ein Leben für die Literatur',
      'Familie trauert um tödlich verunglückten Sohn',
      'Zahl der Suizide unter Jugendlichen gestiegen',
      'Ex-Fußballprofi überraschend verstorben Der frühere Nationalspieler wurde nur 54 Jahre alt',
      'Begräbnis des Altbundespräsidenten: Tausende nehmen Abschied',
      'Zahl der Todesopfer steigt weiter',
      'Legendärer Rockmusiker nach langer Krankheit gestorben',
    ],
    psyche: [
      'Immer mehr Jugendliche leiden an Depressionen',
      'Burnout und Einsamkeit nehmen stark zu',
      'Angststörungen: Wartezeit auf Therapieplatz beträgt Monate',
      'Essstörungen bei Mädchen haben sich verdoppelt',
      'Psychische Krise nach dem Lockdown: Kinderpsychiatrien überfüllt',
      'Wenn die Seele streikt: Leben mit chronischer Depression Eine Betroffene erzählt von ihrem Alltag',
      'Selbstverletzung: Experten schlagen Alarm',
      'Trauma nach Gewalterfahrung: Viele Opfer bleiben ohne Hilfe',
      'Studie: Social Media verstärkt Angst und Niedergeschlagenheit',
      'Panikattacken im Job: Wie Betroffene damit umgehen',
    ],
    sucht: [
      'Drogentote: Zahl der Überdosen steigt',
      'Spielsucht ruiniert Familien',
      'Fentanyl-Krise: Opioide fordern Tausende Todesopfer',
      'Alkoholabhängigkeit: Immer mehr Frauen betroffen',
      'Kokain im Abwasser: Konsum in Städten auf Rekordniveau',
      'Neue Designerdroge breitet sich unter Jugendlichen aus',
      'Leben mit der Sucht: Wenn das Glücksspiel alles kostet Ein Betroffener schildert, wie er sein Erspartes verspielte',
      'Crystal Meth: Polizei warnt vor gefährlicher Mischung',
      'Rauschgift im Wert von Millionen sichergestellt',
    ],
    diskriminierung: [
      'Rassistischer Angriff auf Familie in der U-Bahn',
      'Hasspostings gegen Minderheit im Netz',
      'Antisemitische Vorfälle erreichen neuen Höchststand',
      'Homophober Übergriff nach Pride-Parade',
      'Politiker sorgt mit fremdenfeindlicher Aussage für Empörung',
      'Studie: Menschen mit Migrationshintergrund werden bei Wohnungssuche benachteiligt',
      'Mobbing an Schulen: Jedes fünfte Kind betroffen',
      'Hetze gegen Flüchtlinge: Ermittlungen wegen Verhetzung Die Polizei prüft Beiträge in sozialen Medien',
      'Frauen verdienen weiterhin deutlich weniger als Männer',
      'Rechtsextreme Parolen bei Fußballspiel: Verband ermittelt',
    ],
    tierleid: [
      'Hunde in verwahrloster Wohnung gefunden',
      'Massentierhaltung: Schweine leiden in engen Ställen',
      'Tiertransport: Kühe tagelang ohne Wasser unterwegs',
      'Grausame Tierquälerei: Katzen vergiftet',
      'Tierversuche: Tausende Mäuse für Forschung getötet',
      'Hundert tote Fische nach Giftunfall im Fluss',
      'Wilderer töten seltene Nashörner',
      'Undercover-Video zeigt Missstände im Schlachthof Tierschützer fordern die sofortige Schließung des Betriebs',
      'Vogelgrippe: Zehntausende Hühner müssen gekeult werden',
    ],
    krankheit: [
      'Krebs: Zahl der Neuerkrankungen steigt',
      'Virus breitet sich aus, Spitäler überlastet',
      'Masern-Ausbruch: Gesundheitsbehörde warnt Eltern',
      'Neue Corona-Variante: Fallzahlen steigen wieder',
      'Tuberkulose-Fälle in Schule bestätigt',
      'Grippewelle: Ärzte melden volle Wartezimmer',
      'Diagnose unheilbar: Leben mit einer seltenen Krankheit',
      'Antibiotikaresistente Keime breiten sich in Kliniken aus Experten warnen vor einer stillen Pandemie',
      'Cholera-Ausbruch nach Überschwemmungen',
      'Tausende Patienten warten auf Operation',
    ],
    wirtschaft: [
      'Firma insolvent: Hunderte verlieren ihren Job',
      'Inflation steigt, Preise für Lebensmittel explodieren',
      'Rezession: Wirtschaft schrumpft das dritte Quartal in Folge',
      'Konzern kündigt massiven Stellenabbau an',
      'Kurzarbeit: Betriebe schicken Tausende nach Hause',
      'Börsencrash: Anleger verlieren Milliarden',
      'Zulieferer schließt Standort, Belegschaft unter Schock Die Mitarbeiter erfuhren bei einer Betriebsversammlung vom Aus',
      'Teuerung: Immer mehr Haushalte können Rechnungen nicht zahlen',
      'Pleitewelle in der Baubranche',
      'Energiepreise belasten Industrie schwer',
    ],
    krise: [
      'Regierungskrise eskaliert nach Korruptionsskandal',
      'Notstand ausgerufen, Lage spitzt sich zu',
      'Skandal um Millionen: Ermittlungen gegen Ex-Minister',
      'Staatskrise: Präsident löst Parlament auf',
      'Korruptionsprozess: Anklage wirft Politiker Bestechlichkeit vor',
      'Eskalation im Handelsstreit: Strafzölle treten in Kraft',
      'Tragödie im Mittelmeer: Flüchtlingsboot gekentert',
      'Versorgungskrise: Medikamente werden knapp',
      'Proteste schlagen in Gewalt um, Polizei setzt Tränengas ein',
    ],
  };

  // Harmlose Meldungen aus allen Ressorts – ähnlich lang und im selben Stil wie die belastenden.
  const NEUTRAL = [
    // Politik-Alltag
    'Parteien einigen sich auf Termin für die Landtagswahl',
    'Nationalrat beschließt neues Schulgesetz',
    'Ministerin präsentiert Pläne für Pflegereform',
    'Koalition streitet über die Verteilung des Budgets',
    'Neuer Bürgermeister in Graz angelobt',
    'Partei wählt neue Vorsitzende mit großer Mehrheit',
    'Umfrage: Wer liegt bei der Wahl vorne?',
    'Regierung stellt Entlastungspaket für Familien vor Die Maßnahmen sollen ab Jänner gelten und vor allem Alleinerziehenden helfen',
    'EU-Gipfel berät über gemeinsame Energiepolitik',
    'Opposition kritisiert Pläne zur Steuerreform',
    'Bundespräsident empfängt Staatsgast in der Hofburg',
    'Gemeinderat genehmigt neuen Kindergarten',
    'Diplomatisches Treffen: Außenminister reist nach Brüssel',
    'Personaldebatte in der Partei: Wer folgt auf den Vorsitzenden?',
    // Wirtschaft-Alltag
    'Handelskette sucht 500 neue Lehrlinge',
    'Neue Filiale eröffnet in der Innenstadt',
    'Autobauer stellt neues Elektromodell vor',
    'Bank senkt Zinsen für Sparbücher leicht',
    'Tourismus: Gute Buchungslage für die Wintersaison',
    'Start-up aus Wien gewinnt Innovationspreis',
    'Bahn kauft neue Züge für den Nahverkehr',
    'Umfrage: So viel geben Österreicher für Weihnachtsgeschenke aus',
    'Konzern meldet höheren Umsatz im dritten Quartal',
    'Lebensmittelhändler erweitert sein Bio-Sortiment',
    'Neue Fluglinie verbindet Wien mit Lissabon',
    'Energieversorger baut Photovoltaik-Anlage auf Deponie Die Anlage soll künftig 3.000 Haushalte mit Strom versorgen',
    'Möbelhaus eröffnet Standort in Linz',
    'Firmenporträt: Familienbetrieb feiert hundertjähriges Bestehen',
    'Homeoffice: Wie Betriebe ihre Büros umbauen',
    'Brauerei bringt alkoholfreies Bier auf den Markt',
    'Börse: Technologiewerte legen zu',
    'Neue Kassensysteme: Supermärkte setzen auf Selbstbedienung',
    // Wissenschaft und Technik
    'Forscher entdecken neue Käferart im Regenwald',
    'Weltraumteleskop liefert Bilder ferner Galaxien',
    'Archäologen finden römische Münzen bei Ausgrabung',
    'Studie: Kaffee am Morgen macht wacher',
    'Neues Smartphone im Test: Starke Kamera, schwacher Akku',
    'Rakete bringt Satelliten erfolgreich ins All',
    'Wie Vögel sich auf ihren Zugrouten orientieren',
    'Physiker messen Eigenschaften eines seltenen Teilchens',
    'Neue Methode macht Batterien langlebiger',
    'Komet wird im Dezember mit freiem Auge sichtbar sein Astronomen empfehlen einen Blick in den Abendhimmel',
    'Fachhochschule startet neuen Studiengang für Robotik',
    'Warum Katzen schnurren: Forscher haben eine Erklärung',
    'Videospiel im Test: Liebevolle Welt, kurze Spielzeit',
    'Raumstation: Astronautin führt Experimente mit Pflanzen durch',
    'Warum Bienen im Winter nicht erfrieren',
    'Mathematiker lösen jahrzehntealtes Rätsel',
    'Wie Tintenfische ihre Farbe wechseln',
    'Dinosaurierfund begeistert Paläontologen',
    // Sport
    'Rapid gewinnt Derby gegen Austria mit 2:1',
    'Skirennläuferin feiert ersten Weltcupsieg',
    'Rennfahrer gewinnt in Monza nach spannendem Finish',
    'Handball: Österreich besiegt Norwegen knapp',
    'Golferin spielt sich in die Top Ten',
    'Eishockey: Salzburg übernimmt die Tabellenführung',
    'Trainerwechsel beim Tabellenletzten',
    'Teamchef nominiert Kader für die Länderspiele Drei junge Spieler stehen erstmals im Aufgebot',
    'Basketball: Klarer Heimsieg zum Saisonauftakt',
    'Marathon: Rekordbeteiligung in Wien',
    'Champions League: Spätes Tor sichert Punkt',
    'Formel 1: Hamilton gewinnt im Regen',
    'Volleyball: Meister verteidigt den Titel',
    'Fußballklub präsentiert neuen Sportdirektor',
    'Schiedsrichterentscheidung sorgt für Diskussionen',
    'Radprofi wechselt zu neuem Team',
    'Analyse: Warum die Abwehr nicht funktionierte',
    'Fans feiern Aufstieg in die erste Liga',
    // Kultur und Medien
    'Wiener Philharmoniker spielen Open-Air-Konzert',
    'Museum zeigt Werke von Gustav Klimt',
    'Neuer Kinofilm über das Leben eines Komponisten',
    'Buchtipps der Woche: Romane für den Herbst',
    'Theaterpremiere: Shakespeare in moderner Fassung',
    'Band kündigt neues Album und Tournee an',
    'Festival lockt Tausende Besucher an',
    'Schauspielerin erhält Preis für ihr Lebenswerk',
    'Streaming-Tipps für das Wochenende',
    'Fotoausstellung zeigt Porträts von Wiener Kaffeehausbesitzern Die Schau ist bis Ende Jänner im Museumsquartier zu sehen',
    'Kabarettist feiert Bühnenjubiläum',
    'Literaturpreis geht an junge Autorin',
    'Serienkritik: Spannend bis zur letzten Folge',
    'Oper: Gelungene Premiere an der Staatsoper',
    'Kolumne: Gedanken zum Sonntag',
    'Interview mit einem Regisseur über seinen neuen Film',
    // Lokales und Alltag
    'Neue Straßenbahnlinie verbindet zwei Bezirke',
    'Wetter: Sonniges Wochenende mit bis zu 25 Grad',
    'Stadt eröffnet neuen Radweg entlang des Flusses',
    'Schulstart: Was Eltern wissen müssen',
    'Bücherei verlängert ihre Öffnungszeiten',
    'Baustelle: Umleitungen in der Innenstadt',
    'Christkindlmarkt öffnet seine Tore',
    'Neues Hallenbad nach Renovierung wiedereröffnet',
    'Gemeinde baut 300 leistbare Wohnungen',
    'Bahnhof wird bis Herbst umgebaut',
    'Verkehr: Ab Montag gilt neue Kurzparkzone',
    'Feuerwehrfest mit Musik und Kinderprogramm',
    // Leben, Gesundheit-Alltag, Freizeit
    'Rezept: So gelingt der perfekte Kaiserschmarrn',
    'Tipps für den Herbsturlaub in der Steiermark',
    'Tiergarten freut sich über Pandababy',
    'Pferdeshow begeistert das Publikum',
    'Wandern: Die schönsten Routen im Salzkammergut',
    'Balkon: Welche Kräuter auch im Schatten wachsen',
    'So bleibt man im Alter fit und beweglich',
    'Gesunde Ernährung: Was Kinder wirklich brauchen',
    'Reisen: Günstig mit dem Zug durch Europa',
    'Wohnen: Kleine Wohnung clever einrichten',
    'Restaurantkritik: Gutes Essen, lange Wartezeit',
    'Mode: Diese Farben sind im Winter angesagt',
    'Schlaf: Warum ein Mittagsschläfchen gut tut',
    'Haustiere: Was kostet ein Hund im Jahr?',
    'Die besten Wanderwege für Familien mit Kindern',
    // Forum / Community / Ratgeber
    'Was ist euer Lieblingsrezept für den Herbst?',
    'Welche Serien schaut ihr gerade?',
    'Eure Tipps für den ersten Urlaub mit Kind?',
    'Welches E-Auto könnt ihr empfehlen?',
    'Wie organisiert ihr euren Haushalt?',
    'Ratgeber: Was tun, wenn der Vermieter die Kaution nicht zurückzahlt?',
    'Recht: Wem gehört der Baum an der Grundstücksgrenze?',
    'Quiz: Wie gut kennen Sie Österreichs Berge?',
    'Rätsel und Sudoku für das Wochenende',
    'Leserfotos: Die schönsten Herbstbilder',
    // Geschichte
    'Vor 100 Jahren: Die erste Radiosendung in Österreich',
    'Wie die Habsburger ihre Hochzeiten feierten',
    'Archiv: Alte Fotos zeigen Wien im Wandel',
    'Die Geschichte der Sachertorte',
  ];

  /** Beispiele der angegebenen Themen. */
  function badFor(ids) {
    const out = [];
    for (const id of ids || []) if (BAD[id]) out.push(...BAD[id]);
    return out;
  }

  root.SFExamples = { BAD, NEUTRAL, badFor };
  if (typeof module !== 'undefined' && module.exports) module.exports = root.SFExamples;
})(typeof globalThis !== 'undefined' ? globalThis : this);
